spring.application.name=Currency

spring.datasource.url=jdbc:mysql://localhost:3306/currency
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.web.resources.static-locations=classpath:/templates/
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html

spring.cache.type=simple
logging.level.org.springframework.cache=DEBUG
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator

spring.docker.compose.enabled=false
